version: "3.3"
services:
    app:
        build:
            .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        working_dir: /app
        command:
            "uvicorn main:app --reload --host 0.0.0.0"
